### ISSUE TITLE
Failed building wheel for littlefs-python

### ISSUE THREAD

**Issue by Massimiliano-solutiontech** [joltwallet/esp_littlefs#244]
I can't build a project due to `Failed building wheel for littlefs-python`. I'm using `esp-idf v5.5.1` `joltwallet/littlefs v1.20.1` `Python v3.14.0`

This is the CMakeLists.txt

```cmake
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    fail_at_build_time(littlefs "Windows does not support LittleFS partition generation")
else()
    littlefs_create_partition_image(spiffs ../flash_data FLASH_IN_PROJECT)
endif()
```

<details>
<summary>Build log</summary>

```log
[1260/1267] Generating ../../littlefs_py_venv
FAILED: [code=1] littlefs_py_venv [REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv 
cd [REDACTED]/build/dev-TwoPointzeroNG/esp-idf/main && [REDACTED]/.espressif/python_env/idf5.5_py3.14_env/bin/python -m venv [REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv && [REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv/bin/pip install -r [REDACTED]/managed_components/joltwallet__littlefs/image-building-requirements.txt
Collecting littlefs-python==0.13.3 (from -r [REDACTED]/managed_components/joltwallet__littlefs/image-building-requirements.txt (line 1))
  Using cached littlefs_python-0.13.3.tar.gz (507 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: littlefs-python
  Building wheel for littlefs-python (pyproject.toml): started
  Building wheel for littlefs-python (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for littlefs-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [232 lines of output]
      toml section missing PosixPath('pyproject.toml') does not contain a tool.setuptools_scm section
      toml section missing PosixPath('pyproject.toml') does not contain a tool.setuptools_scm section
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/__init__.py -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/context.py -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/errors.py -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/__main__.py -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/lfs.pyi -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      copying src/littlefs/py.typed -> build/lib.macosx-26.0-arm64-cpython-314/littlefs
      running build_ext
      building 'littlefs.lfs' extension
      creating build/temp.macosx-26.0-arm64-cpython-314/littlefs
      creating build/temp.macosx-26.0-arm64-cpython-314/src/littlefs
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -DLFS_MULTIVERSION=1 -DLFS_NAME_MAX=1022 -Ilittlefs -I[REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv/include -I/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14 -c littlefs/lfs.c -o build/temp.macosx-26.0-arm64-cpython-314/littlefs/lfs.o -std=c99 -UNDEBUG
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -DLFS_MULTIVERSION=1 -DLFS_NAME_MAX=1022 -Ilittlefs -I[REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv/include -I/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14 -c littlefs/lfs_util.c -o build/temp.macosx-26.0-arm64-cpython-314/littlefs/lfs_util.o -std=c99 -UNDEBUG
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -DLFS_MULTIVERSION=1 -DLFS_NAME_MAX=1022 -Ilittlefs -I[REDACTED]/build/dev-TwoPointzeroNG/littlefs_py_venv/include -I/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14 -c src/littlefs/lfs.c -o build/temp.macosx-26.0-arm64-cpython-314/src/littlefs/lfs.o -std=c99 -UNDEBUG
      src/littlefs/lfs.c:432:39: error: expression is not an integer constant expression
        432 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
            |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/littlefs/lfs.c:432:41: note: division by zero
        432 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
            |                                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
       8700 |         __pyx_t_1 = __Pyx_GetItemInt(__pyx_v_result, 0, long, 1, __Pyx_PyLong_From_long, 0, 0, 1, 1); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 502, __pyx_L5_except_error)
            |                     ^
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1198:28: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1198 |           likely(v < (type)PY_SSIZE_T_MAX ||\
            |                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1199:29: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1199 |                  v == (type)PY_SSIZE_T_MAX)  &&\
            |                             ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1200:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1200 |           (!is_signed || likely(v > (type)PY_SSIZE_T_MIN ||\
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1201:44: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1201 |                                 v == (type)PY_SSIZE_T_MIN)))  ||\
            |                                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1203:42: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1203 |           (is_signed || likely(v < (type)PY_SSIZE_T_MAX ||\
            |                                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:8700:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2193:6: note: expanded from macro '__Pyx_GetItemInt'
       2193 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1204:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1204 |                                v == (type)PY_SSIZE_T_MAX)))  )
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
       11547 |       if (unlikely((__Pyx_SetItemInt(__pyx_v_result, __pyx_v_idx, __pyx_v_item, Py_ssize_t, 1, PyLong_FromSsize_t, 1, 1, 1, 1) < 0))) __PYX_ERR(1, 694, __pyx_L1_error)
             |                     ^
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1198:28: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1198 |           likely(v < (type)PY_SSIZE_T_MAX ||\
            |                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1199:29: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1199 |                  v == (type)PY_SSIZE_T_MAX)  &&\
            |                             ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1200:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1200 |           (!is_signed || likely(v > (type)PY_SSIZE_T_MIN ||\
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1201:44: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1201 |                                 v == (type)PY_SSIZE_T_MIN)))  ||\
            |                                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1203:42: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1203 |           (is_signed || likely(v < (type)PY_SSIZE_T_MAX ||\
            |                                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:11547:21: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2425:6: note: expanded from macro '__Pyx_SetItemInt'
       2425 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1204:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1204 |                                v == (type)PY_SSIZE_T_MAX)))  )
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
       17348 |   __pyx_t_1 = __Pyx_GetItemInt_Tuple(__pyx_v___pyx_state, 0, long, 1, __Pyx_PyLong_From_long, 0, 0, 1, 1); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 12, __pyx_L1_error)
             |               ^
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1198:28: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1198 |           likely(v < (type)PY_SSIZE_T_MAX ||\
            |                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1199:29: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1199 |                  v == (type)PY_SSIZE_T_MAX)  &&\
            |                             ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1200:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1200 |           (!is_signed || likely(v > (type)PY_SSIZE_T_MIN ||\
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1201:44: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1201 |                                 v == (type)PY_SSIZE_T_MIN)))  ||\
            |                                            ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:165:26: note: expanded from macro 'PY_SSIZE_T_MIN'
        165 | #define PY_SSIZE_T_MIN (-PY_SSIZE_T_MAX-1)
            |                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1203:42: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1203 |           (is_signed || likely(v < (type)PY_SSIZE_T_MAX ||\
            |                                          ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      src/littlefs/lfs.c:17348:15: error: use of undeclared identifier 'SSIZE_MAX'
      src/littlefs/lfs.c:2204:6: note: expanded from macro '__Pyx_GetItemInt_Tuple'
       2204 |     (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
            |      ^
      src/littlefs/lfs.c:1204:43: note: expanded from macro '__Pyx_fits_Py_ssize_t'
       1204 |                                v == (type)PY_SSIZE_T_MAX)))  )
            |                                           ^
      /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/include/python3.14/pyport.h:156:27: note: expanded from macro 'PY_SSIZE_T_MAX'
        156 | #   define PY_SSIZE_T_MAX SSIZE_MAX
            |                           ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '[REDACTED]/.espressif/tools/esp-clang/esp-19.1.2_20250312/esp-clang/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for littlefs-python
Failed to build littlefs-python
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> littlefs-python
[1261/1267] Generating esp-idf/esp_system/ld/sections.ld
ninja: build stopped: subcommand failed.

 *  The terminal process "ninja" terminated with exit code: 1. 
```
</details>

**Comment by BrianPugh** [comment]
no need; i'm a maintainer over there as well; i'll work on adding python3.14 support today!

**Comment by BrianPugh** [comment]
v2.11.2 has been released
